In [1]:
import matplotlib.pyplot as plt
from pathlib import Path
import pandas as pd
import numpy as np
import os
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.datasets import make_blobs
from sklearn.impute import SimpleImputer

In [2]:
# Read in data from CSV file
morgan_df = pd.read_csv("../Morgan_Weather_Data1.csv")
#morgan_data = pd.read_csv('Morgan_Weather_Data.xlsx')

# Get the sheets
morgan_df.head()

,Date,Morgan SWE,Flood y/n,Flood,Hardscrabble (896) Snow Water Equivalent (in) Start of Day Values,Horse Ridge (533) Snow Water Equivalent (in) Start of Day Values,Kilfoil Creek (1145) Snow Water Equivalent (in) Start of Day Values,UTAH SWE,MorganTemp_Max (°F),MorganTemp_min (°F),MorganTemp_mean (°F),MorganPrecipitation_sum (inch),MorganRain_sum (inch),MorganSnowfall_sum (inch),MorganWindspeed_10m_max (mp/h)
0,10/1/1982,80.0,No,0,NaN,1.9,NaN,1.4,47.1,35.8,40.9,0.464,0.464,0.0,6.5
1,10/2/1982,80.0,No,0,NaN,2.2,NaN,1.4,56.4,34.9,45.7,0.000,0.000,0.0,5.6
2,10/3/1982,80.5,No,0,NaN,2.2,NaN,1.3,61.3,37.3,48.6,0.000,0.000,0.0,4.7
3,10/4/1982,81.0,No,0,NaN,1.9,NaN,1.3,64.8,41.3,51.9,0.094,0.094,0.0,9.1
4,10/5/1982,81.0,No,0,NaN,1.6,NaN,1.2,47.9,37.2,43.4,0.249,0.249,0.0,7.6

In [3]:
# drop nans
morgan_drop_df = morgan_df.dropna()
morgan_drop_df.head()

,Date,Morgan SWE,Flood y/n,Flood,Hardscrabble (896) Snow Water Equivalent (in) Start of Day Values,Horse Ridge (533) Snow Water Equivalent (in) Start of Day Values,Kilfoil Creek (1145) Snow Water Equivalent (in) Start of Day Values,UTAH SWE,MorganTemp_Max (°F),MorganTemp_min (°F),MorganTemp_mean (°F),MorganPrecipitation_sum (inch),MorganRain_sum (inch),MorganSnowfall_sum (inch),MorganWindspeed_10m_max (mp/h)
10121,6/17/2010,98.0,Yes,1,0.0,0.0,0.0,0.4,60.2,38.3,50.5,0.0,0.0,0.0,5.5
10122,6/18/2010,98.5,Yes,1,0.0,0.0,0.0,0.4,73.1,40.2,58.2,0.0,0.0,0.0,5.7
10123,6/19/2010,98.5,Yes,1,0.0,0.0,0.0,0.3,78.1,46.5,64.0,0.0,0.0,0.0,8.1
10124,6/20/2010,98.5,Yes,1,0.0,0.0,0.0,0.2,77.9,50.3,66.2,0.0,0.0,0.0,11.0
10125,6/21/2010,98.5,Yes,1,0.0,0.0,0.0,0.1,71.5,51.7,63.3,0.0,0.0,0.0,9.0

In [4]:
y = morgan_drop_df["Flood"]
X = morgan_drop_df.drop(columns=["Flood", "Date", "Flood y/n"])
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(3503, 12)

In [5]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [6]:
classifier.fit(X_train, y_train)

c:\Users\socce\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(max_iter=200, random_state=1)

In [7]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            0       0
2            0       0
3            0       0
4            1       1
5            0       0
6            0       0
7            0       0
8            1       1
9            0       0
10           1       1
11           0       0
12           1       1
13           0       0
14           0       0
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [8]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9606164383561644

In [9]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.978304310590922
Testing Data Score: 0.9606164383561644

In [10]:
from sklearn.metrics import confusion_matrix, classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.98      0.98       942
           1       0.91      0.88      0.90       226

    accuracy                           0.96      1168
   macro avg       0.94      0.93      0.94      1168
weighted avg       0.96      0.96      0.96      1168