In [1]:
import matplotlib.pyplot as plt
from pathlib import Path
import pandas as pd
import numpy as np
import os
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.datasets import make_blobs
from sklearn.impute import SimpleImputer

In [2]:
# Read in data from CSV file
salt_lake_df = pd.read_csv("../Salt_Lake_Weather_Data2.csv")


# Get the sheets
salt_lake_df.head()

,Date,Avg Salt Lake,Flood y/n,Flood,UTAH SWE,Salt Lake CityTemp_Max (°F),Salt Lake CityTemp_min (°F),Salt Lake CityTemp_mean (°F),Salt Lake CityPrecipitation_sum (inch),Salt Lake CityRain_sum (inch),Salt Lake CitySnowfall_sum (inch),Salt Lake CityWindspeed_10m_max (mp/h),SnowbirdTemp_Max (°F),SnowbirdTemp_min (°F),SnowbirdTemp_mean (°F),SnowbirdPrecipitation_sum (inch),SnowbirdRain_sum (inch),SnowbirdSnowfall_sum (inch),SnowbirdWindspeed_10m_max (mp/h)
0,10/1/1982,94.0,Yes,1,1.4,36.7,26.4,31.5,0.239,0.076,1.216,5.9,49.0,37.8,42.9,0.024,0.024,0.0,7.2
1,10/2/1982,94.5,Yes,1,1.4,46.5,23.8,34.3,0.000,0.000,0.000,3.6,57.0,35.7,46.2,0.000,0.000,0.0,5.5
2,10/3/1982,95.0,Yes,1,1.3,50.9,25.8,37.3,0.000,0.000,0.000,5.7,63.0,36.9,49.5,0.000,0.000,0.0,9.1
3,10/4/1982,95.0,Yes,1,1.3,53.7,30.1,41.4,0.052,0.052,0.000,7.8,66.9,40.5,52.6,0.063,0.063,0.0,12.6
4,10/5/1982,95.5,Yes,1,1.2,37.7,26.8,34.1,0.321,0.131,1.324,6.5,48.5,39.8,44.1,0.323,0.323,0.0,8.1

In [3]:
# drop nans
salt_lake_drop_df = salt_lake_df.dropna()
salt_lake_drop_df.head()

,Date,Avg Salt Lake,Flood y/n,Flood,UTAH SWE,Salt Lake CityTemp_Max (°F),Salt Lake CityTemp_min (°F),Salt Lake CityTemp_mean (°F),Salt Lake CityPrecipitation_sum (inch),Salt Lake CityRain_sum (inch),Salt Lake CitySnowfall_sum (inch),Salt Lake CityWindspeed_10m_max (mp/h),SnowbirdTemp_Max (°F),SnowbirdTemp_min (°F),SnowbirdTemp_mean (°F),SnowbirdPrecipitation_sum (inch),SnowbirdRain_sum (inch),SnowbirdSnowfall_sum (inch),SnowbirdWindspeed_10m_max (mp/h)
0,10/1/1982,94.0,Yes,1,1.4,36.7,26.4,31.5,0.239,0.076,1.216,5.9,49.0,37.8,42.9,0.024,0.024,0.0,7.2
1,10/2/1982,94.5,Yes,1,1.4,46.5,23.8,34.3,0.000,0.000,0.000,3.6,57.0,35.7,46.2,0.000,0.000,0.0,5.5
2,10/3/1982,95.0,Yes,1,1.3,50.9,25.8,37.3,0.000,0.000,0.000,5.7,63.0,36.9,49.5,0.000,0.000,0.0,9.1
3,10/4/1982,95.0,Yes,1,1.3,53.7,30.1,41.4,0.052,0.052,0.000,7.8,66.9,40.5,52.6,0.063,0.063,0.0,12.6
4,10/5/1982,95.5,Yes,1,1.2,37.7,26.8,34.1,0.321,0.131,1.324,6.5,48.5,39.8,44.1,0.323,0.323,0.0,8.1

In [4]:
y = salt_lake_drop_df["Flood"]
X = salt_lake_drop_df.drop(columns=["Flood", "Date", "Flood y/n"])
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(11094, 16)

In [5]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [6]:
classifier.fit(X_train, y_train)

c:\Users\socce\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(max_iter=200, random_state=1)

In [7]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            1       1
2            0       0
3            0       0
4            0       1
5            1       1
6            1       1
7            0       0
8            0       0
9            0       0
10           1       1
11           0       0
12           1       1
13           0       0
14           1       1
15           0       0
16           1       0
17           0       0
18           0       0
19           1       1

In [8]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9597079502433749

In [9]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.966197944835046
Testing Data Score: 0.9597079502433749

In [10]:
from sklearn.metrics import confusion_matrix, classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      2315
           1       0.94      0.95      0.95      1383

    accuracy                           0.96      3698
   macro avg       0.96      0.96      0.96      3698
weighted avg       0.96      0.96      0.96      3698