In [2]:
import matplotlib.pyplot as plt
from pathlib import Path
import pandas as pd
import numpy as np
import os
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.datasets import make_blobs
from sklearn.impute import SimpleImputer

In [3]:
# Read in data from CSV file
weber_df = pd.read_csv("../Weber_Weather_Data1.csv")
#morgan_data = pd.read_csv('Morgan_Weather_Data.xlsx')

# Get the sheets
weber_df.head()

,Date,Causey Reservoir (10137290) % of Reservoir Capacity Start of Day Values,Pineview Reservoir (10139000) % of Reservoir Capacity Start of Day Values,Weber SWE,Unnamed: 4,Flood,Ben Lomond Peak (332) Snow Water Equivalent (in) Start of Day Values,Ben Lomond Trail (333) Snow Water Equivalent (in) Start of Day Values,Lightning Ridge (1056) Snow Water Equivalent (in) Start of Day Values,UTAH SWE,...,OgdenRain_sum (inch),OgdenSnowfall_sum (inch),OgdenWindspeed_10m_max (mp/h),hooperTemp_Max (°F),hooperTemp_min (°F),hooperTemp_mean (°F),hooperPrecipitation_sum (inch),hooperRain_sum (inch),hooperSnowfall_sum (inch),hooperWindspeed_10m_max (mp/h)
0,10/1/1982,56,70,63.0,No,0,2.5,1.0,NaN,1.4,...,0.387,0.0,10.8,49.5,44.0,46.7,0.239,0.239,0.0,14.0
1,10/2/1982,56,70,63.0,No,0,3.1,1.0,NaN,1.4,...,0.000,0.0,8.2,56.3,44.0,50.7,0.000,0.000,0.0,9.3
2,10/3/1982,56,70,63.0,No,0,2.9,0.9,NaN,1.3,...,0.000,0.0,5.1,57.4,44.9,51.5,0.000,0.000,0.0,5.2
3,10/4/1982,56,70,63.0,No,0,2.7,0.6,NaN,1.3,...,0.056,0.0,8.9,62.2,48.9,55.3,0.036,0.036,0.0,11.6
4,10/5/1982,44,70,57.0,No,0,2.5,0.2,NaN,1.2,...,0.115,0.0,8.1,50.0,43.8,47.4,0.084,0.084,0.0,11.9

In [4]:
# drop nans
weber_drop_df = weber_df.dropna()
weber_drop_df.head()

,Date,Causey Reservoir (10137290) % of Reservoir Capacity Start of Day Values,Pineview Reservoir (10139000) % of Reservoir Capacity Start of Day Values,Weber SWE,Unnamed: 4,Flood,Ben Lomond Peak (332) Snow Water Equivalent (in) Start of Day Values,Ben Lomond Trail (333) Snow Water Equivalent (in) Start of Day Values,Lightning Ridge (1056) Snow Water Equivalent (in) Start of Day Values,UTAH SWE,...,OgdenRain_sum (inch),OgdenSnowfall_sum (inch),OgdenWindspeed_10m_max (mp/h),hooperTemp_Max (°F),hooperTemp_min (°F),hooperTemp_mean (°F),hooperPrecipitation_sum (inch),hooperRain_sum (inch),hooperSnowfall_sum (inch),hooperWindspeed_10m_max (mp/h)
7962,7/19/2004,86,80,83.0,No,0,0.0,0.0,0.0,0.0,...,0.000,0.0,5.6,84.7,71.4,79.7,0.000,0.000,0.0,5.6
7963,7/20/2004,85,80,82.5,No,0,0.0,0.0,0.0,0.0,...,0.078,0.0,6.8,84.1,74.9,80.5,0.060,0.060,0.0,10.5
7964,7/21/2004,84,79,81.5,No,0,0.0,0.0,0.0,0.0,...,0.000,0.0,6.7,85.6,73.3,80.6,0.000,0.000,0.0,7.0
7965,7/22/2004,82,79,80.5,No,0,0.0,0.0,0.0,0.0,...,0.000,0.0,9.3,88.2,71.8,81.9,0.059,0.059,0.0,12.3
7966,7/23/2004,81,79,80.0,No,0,0.0,0.0,0.0,0.0,...,0.000,0.0,6.0,84.2,69.8,78.9,0.000,0.000,0.0,7.0

In [7]:
y = weber_drop_df["Flood"]
X = weber_drop_df.drop(columns=["Flood", "Date", "Unnamed: 4"])
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(5122, 21)

In [8]:
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

In [9]:
classifier.fit(X_train, y_train)

c:\Users\socce\anaconda3\envs\mlenv\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression(max_iter=200, random_state=1)

In [10]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

    Prediction  Actual
0            0       0
1            1       1
2            0       0
3            0       0
4            0       0
5            0       0
6            0       0
7            1       1
8            1       1
9            0       0
10           0       0
11           0       0
12           0       0
13           0       0
14           0       0
15           0       0
16           0       0
17           0       0
18           0       0
19           0       0

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9607728337236534

In [12]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9621241702459976
Testing Data Score: 0.9607728337236534

In [14]:
from sklearn.metrics import confusion_matrix, classification_report
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.97      0.98      0.98      1365
           1       0.91      0.90      0.90       343

    accuracy                           0.96      1708
   macro avg       0.94      0.94      0.94      1708
weighted avg       0.96      0.96      0.96      1708